apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Odoo Builder Image
  generation: 13
  name: doodba
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Odoo application.
      iconClass: icon-python
      openshift.io/display-name: odoo-latest
      sampleRepo: https://github.com/oondeo/oondeo/doodba-scaffolding.git
      supports: odoo:latest,odoo
      tags: builder,odoo
      version: "latest"
    from:
      kind: DockerImage
      name: docker.io/oondeo/doodba:latest
    importPolicy: {}
    name: "latest"
    referencePolicy:
      type: Source
  - annotations:
      description: Odoo application.
      iconClass: icon-python
      openshift.io/display-name: odoo-11
      sampleRepo: https://github.com/oondeo/oondeo/doodba-scaffolding.git
      supports: odoo:11,odoo
      tags: builder,odoo
      version: "11.0"
    from:
      kind: DockerImage
      name: docker.io/oondeo/doodba:11.0
    importPolicy: {}
    name: "11.0"
    referencePolicy:
      type: Source
  - annotations:
      description: Odoo application.
      iconClass: icon-python
      openshift.io/display-name: odoo-12.0
      sampleRepo: https://github.com/oondeo/oondeo/doodba-scaffolding.git
      supports: odoo:12.0,odoo
      tags: builder,odoo
      version: "12.0"
    from:
      kind: DockerImage
      name: docker.io/oondeo/doodba:12.0
    importPolicy: {}
    name: "12.0"
    referencePolicy:
      type: Source      
