#!/usr/bin/env sh

echo "------ HOOK START - POST_CHECKOUT -------"
git submodule update --init --recursive --remote
# git submodule foreach git pull origin master
if [ "$BUILD_DIR" != "" ]
then
    cp -a "$(dirname $0)/$BUILD_DIR" "$(dirname $0)/../../"
fi
echo "------ HOOK END - POST_CHECKOUT -------"
